### ISSUE TITLE
Newlines aren't required after variable declarations

### ISSUE THREAD

**Issue by zofrex** [alexcrichton/toml-rs#100]
Here's some of the examples my automated testing with afl-fuzz spat out - these are all accepted as valid by toml-rs and rejected as invalid by pytoml:

```
0=0r=false
```

```
0=""o=""m=""r=""00="0"q="""0"""e="""0"""
```

```
[[0000l0]]
0="0"[[0000l0]]
0="0"[[0000l0]]
0="0"l="0"
```

```
0=[0]00=[0,0,0]t=["0","0","0"]s=[1000-00-00T00:00:00Z,2000-00-00T00:00:00Z]
```

```
0=0r0=0r=false
```

```
0=0r0=0r=falsefal=false
```

I've included a representative set of examples in case there's multiple bugs here.

**Comment by alexcrichton** [comment]
Oh dear, seems bad!

**Comment by zofrex** [comment]
I'm wondering if the spec being misleading or ambiguous is the real bug, I've found this same issue in two other implementations!
