### ISSUE TITLE
lookup*() have incorrect lifetime specifiers

### ISSUE THREAD

**Issue by MarkSwanson** [alexcrichton/toml-rs#102]
Current signature:     pub fn lookup<'a>(&'a self, path: &'a str) -> Option<&'a Value> 

A better signature:     pub fn lookup<'a, 'b>(&'a self, path: &'b str) -> Option<&'a Value> 

Rationale:
- the path has nothing to do with the result.
- the path has no need to live as long as the Value/self.

The current signature is a problem because:
I can't even create a path to use lookup() because of the lifetime restriction. Example:

    pub fn get_config_string<'a, 'b>(config: &'a Value, key: &'b str) -> Result<&'a str, MyError> {
        let path = format!("init.{}", &key);
        config.lookup(&path) <-- fails

Obviously it is "impossible" to create path with the required lifetime 'a.
(I need to limit lookups to subsets of a Value)

I've created my own branch with the 'better signature' and it works fine.
I can't see any downsides. Can you?

Thanks!

**Comment by alexcrichton** [comment]
Oh dear yes indeed! Wanna send a PR for this? Could probably even take advantage of lifetime elision and just remove the lifetimes altogether
