### ISSUE TITLE
Toml <-> JSON translation?

### ISSUE THREAD

**Issue by matthiasbeyer** [alexcrichton/toml-rs#106]
I'm not sure whether this is possible, feasible or in scope of this crate.

It would be nice to have a TOML <-> JSON translation (or more generic translation via serde to JSON, XML, YAML, whatever works). I care mostely about JSON, though.

How can I convince you? :smile:

**Comment by alexcrichton** [comment]
In addition to what @dtolnay mentioned, if you're using rustc-serialize there's an [example in the repo](https://github.com/alexcrichton/toml-rs/blob/master/examples/toml2json.rs) of how to do this.

**Comment by alexcrichton** [comment]
Given that this is built-in to serde and there's an example, I'm going to close this.
