### ISSUE TITLE
2.1: Newline character before table removed

### ISSUE THREAD

**Issue by matthiasbeyer** [alexcrichton/toml-rs#113]
The latest release notes:

```
* Don't emit leading spaces in the serialization of tables or arrays.
```

But leading newline characters are removed as well.. Is this intended?

**Comment by alexcrichton** [comment]
Ah yes sorry, that actually should have said "leading newlines" rather than leading spaces!

**Comment by matthiasbeyer** [comment]
Okay, so https://github.com/matthiasbeyer/imag/issues/729 was the right fix.

---

One could argue now about the version increment - From my point of view, this is a breaking change and should result in `(x + 1).y` instead of `x.(y + 1)`. But now it is too late, I don't blame you! :smile:

**Comment by alexcrichton** [comment]
Sorry for the breakage it definitely wasn't intended!

**Comment by matthiasbeyer** [comment]
Not a big deal as imag isn't released yet. But that tells me that for a release, I want to fix all dependency-versions to a fixed version, so the version-string in the `Cargo.toml` does not contain `"*"`s anymore!

**Comment by nabijaczleweli** [comment]
Well, it didn't break any APIs nor the output format's correctness...
