### ISSUE TITLE
mechanism to leave part of the toml unparsed

### ISSUE THREAD

**Issue by jdc2172** [alexcrichton/toml-rs#115]
Maybe im missing it, but im looking for a mechanism to leave part of the toml unparsed, which allows rust to accept dynamic input. For instance, something akin to labeling a struct field type as `interface{}` in go's json parser.

For example, you cant do something like:
```
#[derive(RustcDecodable)]
struct A {
  v: Value,
}
```
and then decode the toml::Value manually afterwards because `Value` is not `Decodable`

is there an easy mechanism to delay parsing?

**Comment by alexcrichton** [comment]
There's a few avenues to do this currently:

1. You can work with the decoder directly, which should leave behind any unused TOML fields and tables after parsing (this is how Cargo implements "unused key" warnings).
2. You can also use Serde to decode directly into a `Value` which rustc-serialize unfortunately isn't capable of doing.

**Comment by jdc2172** [comment]
Thanks for the help. (1) is a tad verbose, so I'll stick with (2) for now

**Comment by alexcrichton** [comment]
Ok sounds good to me!
