### ISSUE TITLE
allow configuration when encoding to strings

### ISSUE THREAD

**Issue by vitiral** [alexcrichton/toml-rs#119]
The use case I am trying to meet is the ability to configure `toml` to use tripple quotes (`'''`) when useful (such as when there are any newlines.

Here is some example code:
```
extern crate rustc_serialize;
extern crate toml;

use toml::{encode_str};

#[derive(RustcEncodable)]
struct MyStruct { foo: isize, bar: String }

const LONG_TEXT: &'static str = r#"
this is some text
here is some more
yay
"#;

fn main() {
    let my_struct = MyStruct { foo: 4, bar: LONG_TEXT.to_string() };
    println!("{}", encode_str(&my_struct));
}
```

This currently prints:
```
bar = "\nthis is some text\nhere is some more\nyay\n"
foo = 4
```

I would like for it to be able to print:
```
bar = '''
this is some text
here is some more
yay
'''
foo = 4
```

**Comment by vitiral** [comment]
I would think the API for this would be nearly identical to [Encoder::new_pretty()](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/struct.Encoder.html#method.new_pretty) from `rustc_serialize::json`

**Comment by alexcrichton** [comment]
Agreed would be nice to have!

**Comment by vitiral** [comment]
I can try to work on this if you are on board. I really need it for  [rst](https://github.com/vitiral/rst)

**Comment by alexcrichton** [comment]
Sure!

**Comment by vitiral** [comment]
I take that back... after spending a few hours trying to understand how to do this I am at a loss.

What I want to do is do something similar to `rustc_serialze/src/json.rs::emit_enum_variant` except I only have to do something special when the type is a `Value::String`.

However, this does not seem to be possible, as the `Value` object doesn't exist, instead it is replaced with a `Table` object (`Encoder.toml`). Even if I were able to do a match statement on the Value, I don't have access to the `Writer` object like `rustc_serialize` does (on that note, I'm not entirely sure how you are writing data out at all)

Other options have also not panned out. For instance, I thought of overriding the `encode` method on `Value` (in `src/rustc_serialize.rs`), however THAT has the issue that I don't have access to the `writer` either.

I'm at an impass, I feel like some kind of refactoring has to happen to get this functionality:
 - use a `Value` instead of a `Table` for `Encoder.toml`
 - attach a `Writer` attribute to `Encoder`

Other suggestions would be helpful.

**Comment by alexcrichton** [comment]
Oh I figured that whatever the destination is for writing would be threaded through method calls and such instead of owned by any one frame in particular?

**Comment by vitiral** [comment]
I'm not sure what you mean. First of all I don't think you could thread serialization... doesn't it kind of have to be done serially? 

Second of all, I'm just suggesting we use the same implementation as rustc_serialize does for its json module

**Comment by alexcrichton** [comment]
Yeah in any case the same implementation as rustc-serialize should do the job

**Comment by vitiral** [comment]
the rustc_serialize encoder uses a reference to the writer object, which has a lifetime `'a``. This will actually change the type signature of the Encoder object, which COULD negatively affect users.

Would like your opinion -- it is possible that this change might be a breaking change requiring a minor version bump.

**Comment by vitiral** [comment]
Lol, I take back everything I said! I was just *really* confused by the internal API of this package. I think you should *consider* refactoring it to be more in line with how things are done with rustc_serialize, although I think that is out of scope for this ticket (and would require API changes so it should not be done lightly).

Basically my confusion was that your "serialize/encoder" functions don't serialize at all! They convert a rust-type into a `Value` object. In rustc_serialize, the "serialize" functions literally write data to a `fmt::Writer` object -- so they really are serializing!

I now think the changes have to be made in `src/display.rs`. Hopefully this will be a trivial change.

**Comment by alexcrichton** [comment]
Ok, sounds good to me!

**Comment by alexcrichton** [comment]
I've rewritten the parser in the serde 0.9 rewrite https://github.com/alexcrichton/toml-rs/pull/137 and I think it provides a nice vector to implement this through the `Deserializer` type.

**Comment by vitiral** [comment]
Awesome!

**Comment by vitiral** [comment]
I would like to add the suggestion for pretty-printing that lists that would go over some length get flattened:
```
x = [1, 2, 3]
y = ["this is a long list", "I like long lists", "I really like it when they wrap", "yay"]
```

Get's formatted to:
```
x = [1, 2, 3]  # stays the same
y = [
    "this is a long list", 
    "I like long lists", 
    "I really like it when they wrap", 
    "yay"
]
```

**Comment by dtolnay** [comment]
In serde_json we handled this by exposing a [`ser::Formatter`](https://docs.serde.rs/serde_json/ser/trait.Formatter.html) trait that can be used to print JSON according to whatever rules you want. Our built-in compact formatter and pretty formatter are just Formatter implementations, and we don't need to build in configuration for all possible variations of JSON formatting that people may want.

So far this has been an excellent approach that provides maximum performance and maximum flexibility.

See https://github.com/rust-lang-nursery/rustc-serialize/issues/167#issuecomment-276869924 for some example code that implements something similar to @vitiral's use case.

**Comment by alexcrichton** [comment]
Sounds plausible! I'd be open to implementing such a feature for toml as well, but I'm unlikely to do so myself at this time

**Comment by vitiral** [comment]
I think I have a handle on how to do this. I won't be done until at least a few weeks (starting a vacation soon)
