### ISSUE TITLE
be able to specify order when serializing data

### ISSUE THREAD

**Issue by vitiral** [alexcrichton/toml-rs#120]
and perhaps more importantly, preserve order when decoding -> serializing data.

This would require an API change as the value currently wrapped by `Table` is `BTreeMap` which always sorts values alphabetically.

**Comment by alexcrichton** [comment]
This is sort of related to https://github.com/alexcrichton/toml-rs/issues/83, where in general lots of AST information is lost when decoding.

**Comment by alexcrichton** [comment]
I think this is basically done in #137 as serde should be much more flexible than rustc-serialize

**Comment by vitiral** [comment]
That's awesome news, thanks for doing it the *right* way, and so quick!
