### ISSUE TITLE
Document serde feature flag

### ISSUE THREAD

**Issue by ajdlinux** [alexcrichton/toml-rs#122]
I'm currently porting a project over to use serde rather than rustc-serialize, and it took me somewhat longer than it should have before I worked out why the toml Decoder wasn't implementing Deserializer.

It seems it would be a good idea to mention that you should depend on it with `features = ["serde"]` somewhere in the documentation.

**Comment by 0X1A** [comment]
The documentation throughout the library should also reflect supporting serde

**Comment by ajdlinux** [comment]
Thanks @alexcrichton!
