### ISSUE TITLE
Please wrap Vec<ParserError> in a type that implements Error

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/toml-rs#123]
Since the `FromStr` impl for `Value` returns a `Result<Value, Vec<ParserError>>`, and `Vec<ParserError>` doesn't implement Error, it doesn't work well with `try!` or `?`.  Please consider wrapping it in a type that implements `Error` (and `Display` and `Debug`), to simplify error handling.

(This represents a breaking change, like #69, and should likely occur in the same version bump.)

**Comment by alexcrichton** [comment]
I'd love to do this but yeah would require a breaking change, so I'd like to postpone rethinking most of the API of this crate until that happens.

**Comment by alexcrichton** [comment]
I've rewritten the parser in the serde 0.9 rewrite https://github.com/alexcrichton/toml-rs/pull/137 and this should be handled

**Comment by alexcrichton** [comment]
Fixed in #137
