### ISSUE TITLE
Encoding Datetimes as Strings

### ISSUE THREAD

**Issue by alanhdu** [alexcrichton/toml-rs#124]
When I encode `toml::Value::Datetime`s using `toml::encode_str`, they get serialized with quotes which turns them into strings.

```Rust
fn datetime_serialize() {
    let mut table = toml::Table::new();
    table.insert("test".to_string(),
                 toml::Value::Datetime("1979-05-27T07:32:00Z".to_string()));

    // test = "1979-05-27T07:32:00Z"
    println!("{}\n", toml::encode_str(&table));
    // test = 1979-05-27T07:32:00Z
    println!("{}\n", toml::Value::Table(table));  

}
```

Presumably, this is because of https://github.com/alexcrichton/toml-rs/blob/master/src/encoder/rustc_serialize.rs#L218 and https://github.com/alexcrichton/toml-rs/blob/master/src/encoder/serde.rs#L315, although I'm don't know enough about `serde` or `rustc_serialize` to have a solution.

**Comment by alexcrichton** [comment]
Oh I think this is actually expected, we don't really have any other method of encoding a date time via rustc-serialize/serde so the next best approximation is a string. 

With a lack of alternatives I'm going to close this, but I'm open to other suggestions!
