### ISSUE TITLE
Encoding INF and NAN

### ISSUE THREAD

**Issue by alanhdu** [alexcrichton/toml-rs#125]
`toml` will happily serialize `inf` and `nan`, even though both are explicitly barred from the spec. I'm not sure what the right API for exposing this kind of error should be, but this probably shouldn't be allowed happen silently.

```Rust
fn inf_serialize() {
    let mut table = toml::Table::new();
    table.insert("test".to_string(),
                 toml::Value::Datetime("1979-05-27T07:32:00Z".to_string()));

    // test = inf
    println!("{}\n", toml::encode_str(&table));
    // test = inf
    println!("{}\n", toml::Value::Table(table));  

}
```

Found with https://github.com/frewsxcv/afl.rs

**Comment by alexcrichton** [comment]
@alanhdu to clarify, I assume you mean the f64 variants? The example here looks like it's for the previous bug perhaps?
