### ISSUE TITLE
Ability to serialize enums as strings

### ISSUE THREAD

**Issue by netvl** [alexcrichton/toml-rs#133]
According to [serde docs](https://serde.rs/json.html), it is more idiomatic to serialize enums as strings, rather than as numbers. As far as I can see, currently TOML deserializer implementation forces enums to be represented as numbers. Maybe add a flag which would tweak this behavior?

**Comment by alexcrichton** [comment]
Currently the way enums are treated in this crate are as sort of "case statements" when decoding. This crate will attempt to decode each enum variant, returning the first successful one. This means that enums like `Option<T>` decode if the field isn't or is present, and you can otherwise express multiple forms of configuration for one key with an enum value.

Did you see different behavior locally though?

**Comment by netvl** [comment]
I'm not sure what exactly do you mean. What I'm saying is, currently toml-rs forces enums to be serialized/deserialized as numbers. This follows from the error I'm observing, and also from the code. Here is a part of `impl de::Deserializer for Decoder` for enum variants:
```rust
        for variant in 0..variants.len() {
            let mut de = VariantVisitor {
                de: self.sub_decoder(self.toml.clone(), ""),
                variant: variant,
            };
```
Here, `variant` is `usize`. In the `VariantVisitor` there is the following code:
```rust
    fn visit_variant<V>(&mut self) -> Result<V, DecodeError>
        where V: de::Deserialize
    {
        use serde::de::value::ValueDeserializer;

        let mut de = self.variant.into_deserializer();

        de::Deserialize::deserialize(&mut de)
    }
```
Here, the `self.variant` value is turned into a "constant" deserializer which always yields this number to the visitor. This code fails with a type error if the actual TOML document contains a string instead of a number, e.g.
```toml
value = "First"
```
instead of
```toml
value = 0
```
for an enum like
```rust
enum Something {
   First, Second,
}
```

According to serde documentation, this is not how enums are supposed to be serialized.

Maybe I don't understand something, and this code does something else than I think it does, but for the following enum:

```rust
#[derive(Deserialize, Debug, Copy, Clone, PartialEq, Eq)]
pub enum ChangeMode {
    #[serde(rename = "sequential")]
    Sequential,
    #[serde(rename = "random")]
    Random,
}
```

and the following TOML document:
```rust
mode = "random"
```
I'm getting an `invalid type: string` error when using `toml::Decoder`.

**Comment by netvl** [comment]
Hmm, that's interesting. If I change `mode = "random"` to e.g. `mode = 1` in the piece of code I provided in #132, I also get an error about invalid type:
```
Error: invalid type: integer
DecodeError {
    field: None,
    kind: InvalidType(
        "integer"
    )
}
```
How then enums should actually be represented for TOML decoder to understand them?

**Comment by alexcrichton** [comment]
In general the serde TOML behavior is just modeled after the rustc-serialize TOML behavior (quite old at this point). This crate's stance is that it explicitly doesn't support encoding/decoding arbitrary Rust values, but rather instead intends to facilitate ergonomic decoding of values. In that sense enums are interpreted not as rust enums but basically switch statements of how to decode.

**Comment by alexcrichton** [comment]
Ok I'm going to close this because I believe that this is largely a Deserialize/Serialize implementation issue and I think that Serde even has support for attributes like this now?
