### ISSUE TITLE
ValueAfterTable error when not using maps

### ISSUE THREAD

**Issue by bcl** [alexcrichton/toml-rs#145]
I'm fairly sure I'm not doing anything wrong here. I saw the previous discussion about ValueAfterTable and maps, but this is different and seems to be related to the order of the fields. Here's a simple reproducer:

```
extern crate toml;
#[macro_use] extern crate serde_derive;

#[derive(Debug, Serialize, Deserialize)]
pub struct Recipe {
    pub name: String,
    pub description: Option<String>,
    #[serde(default)]
    pub modules: Vec<Modules>,
    #[serde(default)]
    pub packages: Vec<Packages>
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Modules {
    pub name: String,
    pub version: Option<String>
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Packages {
    pub name: String,
    pub version: Option<String>
}

fn main() {
    let recipe_works = toml::from_str::<Recipe>(r#"
        name = "testing"
        description = "example"
        modules = []

        [[packages]]
        name = "base"
    "#).unwrap();
    println!("recipe_works = {:?}", recipe_works);

    let recipe_toml = toml::to_string(&recipe_works).unwrap();
    println!("recipe_toml(works) = {}", recipe_toml);

    let recipe_fails = toml::from_str::<Recipe>(r#"
        name = "testing"
        description = "example"
        packages = []

        [[modules]]
        name = "base"
    "#).unwrap();
    println!("recipe_fails = {:?}", recipe_fails);

    let recipe_toml = toml::to_string(&recipe_fails).unwrap();
    println!("recipe_toml(fails) = {}", recipe_toml);
}
```

The first one works, but when I swap the tables so that packages is empty it fails with:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable'`

**Comment by alexcrichton** [comment]
Ah yeah this is an unfortunate limitation of the current serializer. TOML itself requires values to be emitted before tables, but with serde the order of serialization of `modules` and `packages` is wrong in one situation and right in another here.

To work around this you can serialize to a `toml::Value` and then print that (which handles this internally), or you could implement `ser::Serialize` in a manual fashion which decides which field should be serialized first depending on the values they contain.

**Comment by alexcrichton** [comment]
Another option would be to store `Option<Vec<T>>` and if the vector is empty to omit it, that way if only non-empty vectors of tables are emitted it should always serialize correctly (and deserialize I believe)

**Comment by bcl** [comment]
Thanks for the reply. Do you mean like this?

```
//    let recipe_toml = toml::to_string(&recipe_fails).unwrap();
//    println!("recipe_toml(fails) = {}", recipe_toml);

    let recipe_toml = toml::Value::try_from(recipe_fails).unwrap();
    println!("recipe_toml(fails) = {}", recipe_toml);
```

That also fails with ValueAfterTable error.

**Comment by alexcrichton** [comment]
Oops, looks like that's a bug! Fixed on master now
