### ISSUE TITLE
ParserError at version 3.0

### ISSUE THREAD

**Issue by tredoe** [alexcrichton/toml-rs#146]
At version 3.0, I get `toml::ParserError undefined or not in scope` and it could not find the documentation about such kind of error in [documentation](https://docs.rs/toml/0.3.0/toml/).

**Comment by dtolnay** [comment]
The parsing functions ([`toml::from_str`](https://docs.rs/toml/0.3.0/toml/de/fn.from_str.html) and [`toml::from_slice`](https://docs.rs/toml/0.3.0/toml/de/fn.from_slice.html)) now return [`toml::de::Error`](https://docs.rs/toml/0.3.0/toml/de/struct.Error.html).

**Comment by alexcrichton** [comment]
Ah yeah these have since been renamed, but let me know if the new errors don't suffice!
