### ISSUE TITLE
Getting human-readable string after a failed parse?

### ISSUE THREAD

**Issue by xpe** [alexcrichton/toml-rs#156]
I was hoping to write code like this:

```
// struct Config { ... }

pub fn parse(s: &str) -> Config {
    match toml::from_str(s) {
        Ok(v) => v,
        Err(e) => {
            println!("{}", e.description);
            process::exit(1);
        }
    }
}
```

But `e.description` is not an available field.

I was hoping toml-rs would follow the pattern from:

https://doc.rust-lang.org/nightly/std/error/trait.Error.html#tymethod.description

Is that a sensible thing to ask for? Is there another way to get a human-readable error message?

**Comment by dtolnay** [comment]
The Error trait's `description` that you linked to is a method, not a field:

```rust
println!("{}", e.description());
```

But in my experience the description() method is never what you want so pretend it doesn't exist. For dumb reasons the ordinary Display representation of error types will typically give you much more useful messages.

```rust
println!("{}", e);
```

For example if you have "TOML" that looks like `a: 0` then the description() of the error is "expected a token but found another" while the Display representation is "expected an equals, found a colon at line 1" which is much more helpful.

**Comment by xpe** [comment]
This compiles:

```
use toml;
use std::process;
use std::error::Error;

#[derive(Deserialize)]
pub struct Config {
    pub value: u16,
}

pub fn parse(s: &str) -> Config {
    match toml::from_str(s) {
        Ok(v) => v,
        Err(e) => {
            println!("{}", e.description());
            process::exit(1);
        }
    }
}
```

(posting simultaneously with another answer -- thanks!)

**Comment by xpe** [comment]
Thanks @dtolnay, your suggestions and comments are spot on.
