### ISSUE TITLE
Cannot compile mismatched types and the trait bound `std::borrow::Cow<'_, str>: std::cmp::PartialEq<[std::borrow::Cow<'_, str>]>` is not satisfied

### ISSUE THREAD

**Issue by FractalMatt** [alexcrichton/toml-rs#167]
I realize this is extremely similar to this version, where the recommended fix was upgrading to the newest version of the compiler:
https://github.com/alexcrichton/toml-rs/issues/149

But I'm using Rust 1.16.. and still having the same issue!

Here are the versions of my libraries in the toml, I'm in the process of trying to upgrade iron from v0.4 to v0.5.. and figured I should update everything else.   I probably shouldn't have updated so many libraries at once, I saw one other closed issue suggesting it was possibly another library... though I don't understand how that could trigger an error when compiling toml.

Anyway, help much appreciated, thanks!

Any other suggestions?

```
   Compiling toml v0.4.0
   Compiling staticfile v0.4.0
   Compiling urlencoded v0.5.0
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.4.0/src/de.rs:246:40
    |
246 |                     match t.header.get(..self.depth) {
    |                                        ^^^^^^^^^^^^ expected usize, found struct `std::ops::RangeTo`
    |
    = note: expected type `usize`
    = note:    found type `std::ops::RangeTo<usize>`

error[E0277]: the trait bound `std::borrow::Cow<'_, str>: std::cmp::PartialEq<[std::borrow::Cow<'_, str>]>` is not satisfied
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.4.0/src/de.rs:247:41
    |
247 |                         Some(header) => header == prefix,
    |                                         ^^^^^^^^^^^^^^^^ the trait `std::cmp::PartialEq<[std::borrow::Cow<'_, str>]>` is not implemented for `std::borrow::Cow<'_, str>`
    |
    = help: the following implementations were found:
    = help:   <std::borrow::Cow<'a, std::ffi::OsStr> as std::cmp::PartialEq<std::ffi::OsStr>>
    = help:   <std::borrow::Cow<'a, std::ffi::OsStr> as std::cmp::PartialEq<&'b std::ffi::OsStr>>
    = help:   <std::borrow::Cow<'a, std::ffi::OsStr> as std::cmp::PartialEq<std::ffi::OsString>>
    = help:   <std::borrow::Cow<'a, std::path::Path> as std::cmp::PartialEq<std::path::Path>>
    = help: and 15 others
    = note: required because of the requirements on the impl of `std::cmp::PartialEq<&[std::borrow::Cow<'_, str>]>` for `&std::borrow::Cow<'_, str>`

   Compiling params v0.6.0
error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `toml`.`
```

Finally, here are the libaries I'm using and the versions from the toml:
redis = "^0.8"
iron = "^0.5"
router = "^0.5"
staticfile = "^0.4"
handlebars = "^0.26"
handlebars-iron = "^0.24"
iron-error-router = "^0.3"
handlebars-markdown-helper = "0.5"
mount = "^0.3"
params = "^0.6"
chrono = "^0.3"
time = "^0.1"
rustc-serialize = "^0.3"
rust-crypto = "^0.2"
rand = "^0.3"
lazy_static = "^0.2"
#serde = "^1"
toml = "^0.3"
serde_json = "^1.0"
byteorder = "^1"
regex = "^0.2"

If nobody has suggesting, I'll go back to the old list and upgrade them one at a time and see if a specific one breaks it.

**Comment by FractalMatt** [comment]
Nope... it was definitely upgrading this package from ^0.2 to ^0.4

Thoughts?  Thanks.

**Comment by alexcrichton** [comment]
Can you gist the output of `rustc -vV` to confirm that 1.16.0 is being used?

**Comment by FractalMatt** [comment]
[leo@new-host-2 user-panel]$ rustc -vV
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-unknown-linux-gnu
release: 1.16.0
LLVM version: 3.9

**Comment by alexcrichton** [comment]
Hm that same compiler compiled toml just fine for me, so I'm not sure what's going on in that case :(

**Comment by FractalMatt** [comment]
I figured this one out... I have to compile this specific project as sudo.   It turns out sudo was using an a different version of rust, rust 1.14, and I had to call 'sudo rustup update stable' to update sudo's version of Rust.

Having another issue with this package now but I'll play with that a little and open a separate ticket if still having issues.  Thank you Alex!
