### ISSUE TITLE
Oldest compatible compiler version?

### ISSUE THREAD

**Issue by matthiasbeyer** [alexcrichton/toml-rs#169]
Hi,

what is the oldest compiler version that you support with toml-rs? Is it 1.15 as in the travis.yml file?

Because I'm getting build errors with rust 1.13 on travis, stable works though.

**Comment by dtolnay** [comment]
The newest version of toml requires Rust 1.15 or later. If you need to support Rust 1.13, please use toml 0.2.

**Comment by matthiasbeyer** [comment]
Ah, thanks. No I just updated my codebase to use 0.4, so I just have to bump the compiler on travis to 1.15. Thanks for the fast response! Awesome!
