### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by rap2hpoutre** [alexcrichton/toml-rs#171]
Some functions do not have an example section:

- https://docs.rs/toml/0.4.0/toml/ser/fn.to_vec.html
- https://docs.rs/toml/0.4.0/toml/ser/fn.to_string.html
- https://docs.rs/toml/0.4.0/toml/de/fn.from_slice.html
- https://docs.rs/toml/0.4.0/toml/de/fn.from_str.html

Though these functions are used in TOML index: https://docs.rs/toml/0.4.0/toml/index.html so it's already documented (but not everywhere).

@alexcrichton Do you think we should (I could submit PR) add example to these functions, or is it overkill/useless?

**Comment by alexcrichton** [comment]
Nah this would be awesome! PRs would be most welcome!
