### ISSUE TITLE
Get a position where parse error occured in file

### ISSUE THREAD

**Issue by mersinvald** [alexcrichton/toml-rs#174]
In previous releases there was `line_col(&Error)` method that returned an optional tuple with coordinates in file.

How can I pretty-print `de::Error` with line and collumn for my users to know the position of error now (0.4.0)?
Thank you!

**Comment by alexcrichton** [comment]
Ah I believe this was *just* [added](https://github.com/alexcrichton/toml-rs/pull/170), does that work for your use case?

**Comment by mersinvald** [comment]
@alexcrichton I believe it does, I'll wait for it to land in the next release then.

What do you think about adding line:col printing into Error's Display implementation?

**Comment by alexcrichton** [comment]
@mersinvald oh the [line information](https://github.com/alexcrichton/toml-rs/blob/998eec3e00163df3c85c634c31aa5e88fdbcc0b4/src/de.rs#L1188-L1191) should be displayed at least? I figured that in a generic error message the column wouldn't be too helpful though

**Comment by mersinvald** [comment]
@alexcrichton Turned out I printed only description in my Error type's Display implementation.
Thank you for your help!
