### ISSUE TITLE
Deserializing huge numbers into infinity

### ISSUE THREAD

**Issue by alanhdu** [alexcrichton/toml-rs#181]
`toml` returns a `NumberInvalid` error when to deserialize `inf`, but happily serialize numbers like `99e999` into `inf`:

```rust
extern crate toml;
fn main() {
    let s = "key = 99e9999";
    let data: toml::Value = toml::from_str(s).unwrap();  // fails with "key = inf"
    println!("{}", toml::to_string(&data).unwrap());
}
```

outputs `key = inf`.

Given that `inf` is already explicitly disallowed, I feel like `toml` should also return a `NumberInvalid` error here instead of silently deserializing things into `inf`.

Found with https://github.com/rust-fuzz/targets/pull/72

**Comment by alexcrichton** [comment]
Fixed by https://github.com/alexcrichton/toml-rs/pull/183
