### ISSUE TITLE
Decoding quoted keys with new lines

### ISSUE THREAD

**Issue by alanhdu** [alexcrichton/toml-rs#185]
TOML will happily deserialize 

```toml
"\n" = 5
```

but if you try and serialize it, it will return `toml::ser::Error::KeyNewLine`.

So AFAICT, this behavior is motivated by the [key-newline.toml](https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/key-newline.toml) test, so this might be expected behavior. But for consistency, I feel like either TOML should refuse to deserialize `"\n"` as a key, or to go ahead and serialize it as a quoted string key.

Found with https://github.com/rust-fuzz/targets

**Comment by alexcrichton** [comment]
Aha nice find! I think we should have a special mode of serializing strings here, falling back to this style of escaped newlines for string keys (to make this round-trippable)
