### ISSUE TITLE
How to parse a field which can have different types (string and a table) with serde?

### ISSUE THREAD

**Issue by vityafx** [alexcrichton/toml-rs#189]
I have just noticed that `dependencies` field of a `Cargo.toml` has different kind of values:

    [dependencies]
    libc = "0.2"
    #libc = { path = "../libc" }

So here `libc` is a `string` and it can be actually a `table`. I think it is possible with custom parsing but is there a way to do such a parsing with `toml-rs` with `serde` support?

**Comment by dtolnay** [comment]
Yep, check out https://serde.rs/string-or-struct.html.

**Comment by vityafx** [comment]
Oh, thanks!
