### ISSUE TITLE
Unable to deserialize newtype structs

### ISSUE THREAD

**Issue by Jascha-N** [alexcrichton/toml-rs#196]
Test case:
```rust
#[derive(Deserialize, Serialize)]
struct A {
    b: B
}

#[derive(Deserialize, Serialize)]
struct B(u32);

fn test() {
    let encoded = toml::to_string(&A { b: B(2) }).unwrap();
    toml::from_str::<A>(&encoded).unwrap();
}
```

Results in:
```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: integer `2`, expected tuple struct B", key: ["b"] } }
```

Serialization of newtype structs seems to work fine, but deserialization fails. I'm pretty sure it is expected that serializing followed by deserializing should (almost?) always work, but in any case `toml-rs` should be able to deserialize newtype structs.

**Comment by alexcrichton** [comment]
Thanks for the report!

**Comment by Jascha-N** [comment]
Thanks, but unfortunately I seemed to have reduced the test case too much. There are still issues. 

New test case:
```rust
#[derive(Debug, Deserialize, Serialize)]
struct A {
    b: B
}

#[derive(Debug, Deserialize, Serialize)]
struct B(Option<C>);

#[derive(Debug, Deserialize, Serialize)]
struct C {
    x: u32,
    y: u32,
    z: u32
}

fn main() {
    let input = A { b: B(Some(C { x: 0, y: 1, z: 1 })) };
    println!("{:?}", input);
    let encoded = toml::to_string(&input).unwrap();
    println!("{}", encoded);
    let output = toml::from_str::<A>(&encoded).unwrap();
    println!("{:?}", output);
}
```

Results in:

```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: map, expected tuple struct B", key: ["b"] } }
```

And replacing `input` with `A { b: B(None) }` leads to:

```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `b`", key: [] } }
```

`serde_json` seems to handle these cases fine, but I'd rather not switch to JSON for my configuration files.

**Comment by alexcrichton** [comment]
Ah good points. I believe the first one (with `Some`) is handled with https://github.com/alexcrichton/toml-rs/commit/f6673dfdb3f93bacfbf0c0cab4d78bc4154eec0c although the latter with `None` I'm not sure where it's going awry...
