### ISSUE TITLE
Decoding example does not work.

### ISSUE THREAD

**Issue by Dash83** [alexcrichton/toml-rs#198]
The example in toml-rs/examples/decode.rs seems to be broken.

I created a new project with the exact code from the example, and added the following dependencies in cargo.toml:
[dependencies]
serde = "*"
serde_derive = "*"
toml = "*"

I tried building with the following toolchains:
rustc 1.20.0-nightly (2652ce677 2017-07-17)
rustc 1.18.0 (03fc9d622 2017-06-06)

In both cases, compilation fails with the following error:
error[E0277]: the trait bound `Config: serde::de::Deserialize<'_>` is not satisfied
  --> src/main.rs:51:27
   |
51 |     let decoded: Config = toml::from_str(toml_str).unwrap();
   |                           ^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `Config`
   |
   = note: required by `toml::from_str`

error: aborting due to previous error

error: Could not compile `toml`.

I also tried to build the decoding example in the documentation at https://docs.rs/toml/0.4.2/toml/ and it fails with the same error.

**Comment by Dash83** [comment]
The error seems to be localized to my environment. Closing this as not an issue.

**Comment by shepmaster** [comment]
Pretty sure this is a public / private dependency version mismatch.

**Comment by Dash83** [comment]
It is, @shepmaster. Thanks for the link to your answer, that helped me figure my issue out.
