### ISSUE TITLE
How to parse `[[bin]]` into a struct?

### ISSUE THREAD

**Issue by pornel** [alexcrichton/toml-rs#206]
The documentation doesn't mention how TOML data maps to Rust struct fields when using `#[derive(Deserialize)]`.

While most fields are obvious, parsing of `[[this thing]]` is a mystery to me. I don't know what Rust type it should map to.

I've tried 

```rust
struct CargoManifest {
   bin: Option<Vec<Bin>>
}
struct Bin {
   name: String,
}
```

but `bin` is `None` after parsing a manifest with `[[bin]]`.

**Comment by ehuss** [comment]
This works for me:

```rust
#[macro_use]
extern crate serde_derive;
extern crate toml;

#[derive(Debug, Deserialize)]
struct CargoManifest {
   bin: Option<Vec<Bin>>
}
#[derive(Debug, Deserialize)]
struct Bin {
   name: String,
}

fn main() {
    let s = r#"
[[bin]]
name = "prog"
"#;
    let value: CargoManifest = toml::from_str(s).unwrap();
    println!("{:#?}", value);
}
```

**Comment by pornel** [comment]
Thank you. That was PEBKAC. I was expecting ``[[bin]]` under `[package]` rather than top-level.
