### ISSUE TITLE
Unable to Serialize a struct

### ISSUE THREAD

**Issue by darnir** [alexcrichton/toml-rs#211]
I'm trying to use this library to Serialize a struct I have using `serde`. In the past, I was serializing the struct into a JSON and YAML, but now I'd like to add support for a TOML file.

However, with toml, I get the following error:
```
  --> src/utils/hwdesc.rs:78:21
   |
78 |         .write_all(&toml::to_vec(&hw_desc).expect("Error trying to Serialize"))
   |                     ^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `utils::hwdesc::HardwareDescription`
   |
   = note: required by `toml::to_vec`
```

Note that the same line if I change from `toml::to_vec` to `serde_yaml::to_vec` it works just fine. So the Serialize trait is indeed being derived correctly, just that the `toml` crate seems to have some issue with it

**Comment by dtolnay** [comment]
Check out the checklist and troubleshooting section here https://serde.rs/derive.html.

**Comment by darnir** [comment]
Thanks! Turns out serde-yaml was based off version 0.9.

I've fixed it, and it works now.
