### ISSUE TITLE
Support roundtripping comments

### ISSUE THREAD

**Issue by kivikakk** [alexcrichton/toml-rs#214]
Opening this here from https://github.com/rust-lang/cargo/issues/2183 because I think this is something I'd like to work on, but this repo is a better place to discuss it.

I've worked on plenty of parsers/serializers, but I've never done one that roundtrips comments. This feels super related to #95.

More or less wondering if you've had any more thoughts on this yourself since the original issues! I'm happy to dive in and give it a shot otherwise. I presume I'll want to preserve all line/col information about existing values as a starting point.

**Comment by alexcrichton** [comment]
Thanks for the report! I've considered this sort of functionality under the umbrella of https://github.com/alexcrichton/toml-rs/issues/83 in the past, although unfortunately not a lot of progress in this particular library has happened :(

You may be interested in https://github.com/LeopoldArkham/Molten, however, which I believe is a project to support this.

**Comment by kivikakk** [comment]
Thank you! I'll keep my eyes open there. :)
