### ISSUE TITLE
Unicode escapes only accept upper case hex digits

### ISSUE THREAD

**Issue by avdv** [alexcrichton/toml-rs#240]
For the input:
```
foo = " \uf04b "
```
I was receiving a puzzling error:
```
invalid hex escape character in string: `f`
```
TOML is specified as ABNF:
```
escape-seq-char =/ %x75 4HEXDIG ; uXXXX                U+XXXX
escape-seq-char =/ %x55 8HEXDIG ; UXXXXXXXX            U+XXXXXXXX

HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
```

According to RFC 5234:
>     ABNF strings are case insensitive and the character set for these
>      strings is US-ASCII.
>
>   Hence:
>
>         rulename = "abc"
>
>   and:
>
>         rulename = "aBc"
>
>   will match "abc", "Abc", "aBc", "abC", "ABc", "aBC", "AbC", and
>   "ABC".

So, `\uf04b` and `\uF04B` really should mean the same thing.

**Comment by avdv** [comment]
> Want to send a PR to the upstream ABNF? 

IMO, the upstream ABNF is totally fine, the implementation here is just wrong. `"A"` in ABNF means 'a' or 'A'.

**Comment by alexcrichton** [comment]
Er oops sorry, yes indeed! In that case a PR sounds great!
