### ISSUE TITLE
DateTime Handling as simple String

### ISSUE THREAD

**Issue by mash-graz** [alexcrichton/toml-rs#269]
although i know, that DateTime types are a characteristic part of the TOML specification, and an accurate handling, like in your implementation,  should be seen as desierable in most cases, it isn't always useful.

in my actual project, i just have to parse very simple markdown front matters, and a simple time string would be much more useful than this advanced structure. but the real issue has to be seen in the fact, that this DateTime TOML idiosyncrasies make it very hard, to share and reuse the code with serde JSON and YAML parsers, which would be a much more important goal in this particular case.

to you see an advisable solution, how this default behavior of toml-rs could be modified, to handle Time-Strings just as ordinary string values?

all the solutions e.g. by utilizing `#[serde(deserialize_with = ...] field attributes didn't work, because they will interfere with the other serde parsers. sure -- writing lots of redundant code for all different formats, is always a last resort, but i really would like to figure out a more elegant solution.

**Comment by dtolnay** [comment]
I believe this deserialize_with function does what you are asking.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;
extern crate toml;

use toml::value::Datetime;
use serde::{Deserialize, Deserializer};

#[derive(Deserialize, Debug)]
struct S {
    #[serde(deserialize_with = "maybe_datetime")]
    datetime: String,
}

fn maybe_datetime<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum MaybeDatetime {
        Datetime(Datetime),
        String(String),
    }

    match MaybeDatetime::deserialize(deserializer)? {
        MaybeDatetime::Datetime(datetime) => Ok(datetime.to_string()),
        MaybeDatetime::String(string) => Ok(string),
    }
}

fn main() {
    let t = "datetime = 1979-05-27T07:32:00Z";
    println!("{:?}", toml::from_str::<S>(t).unwrap());

    let j = "{\"datetime\": \"1979-05-27T07:32:00Z\"}";
    println!("{:?}", serde_json::from_str::<S>(j).unwrap());
}
```

**Comment by alexcrichton** [comment]
Indeed I think @dtolnay's snippet should do the trick here!

**Comment by mash-graz** [comment]
@dtolnay 
sorry for my late reply, but your snippet works indeed very well! :)
thanks!
