### ISSUE TITLE
"map key was not a string" for newtype struct

### ISSUE THREAD

**Issue by spease** [alexcrichton/toml-rs#270]
```
#[derive(Serialize)]
pub struct MyType(String);
```

Seems to be the cause of the error. Even though ultimately the newtype should get serialized as a string, it still triggers an error. I'm guessing the problem is in
```impl ser::Serializer for StringExtractor```
as even the serialize_newtype functions immediately return an error as opposed to simply calling the serialize method for the wrapped value.

**Comment by ehuss** [comment]
This appears to be fixed, please reopen if I am misinterpreting.
