### ISSUE TITLE
Allow space after YYYY-MM-DD dates

### ISSUE THREAD

**Issue by Keats** [alexcrichton/toml-rs#273]
The following TOML is currently invalid:

```toml
date = 2018-10-10 
```
Pretty hard to see the issue while looking at it. There is a space after the last digit, causing the parser to return an error as it couldn't parse a datetime.

I had a look at other TOML parsers and some parse it as a date while others error. The grammar seems to indicate that no space should be allowed but that's a bit hard to spot for a human (https://github.com/getzola/zola/issues/525).
If the current behaviour is not going to change, can we get a different error so we can tell the user what to look for?

**Comment by alexcrichton** [comment]
Oh dear, this is indeed a subtle bug! AFAIK the toml grammar does allow spaces after values to the end of the line, so we should definitely accept this. Should just be a minor bug to fix here!

**Comment by ehuss** [comment]
Yea, I think it's my fault when I added space-separated date-times.  I'll fix soon.
