### ISSUE TITLE
inline tables cannot be multi-line

### ISSUE THREAD

**Issue by vitiral** [alexcrichton/toml-rs#281]
Putting this in Cargo.toml:

```
nickel = {·
    git = "https://github.com/nickel-org/nickel.rs"·
}
```

Results in this error:

```
error: failed to parse manifest at `/home/rett/open/artifact/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  expected a table key, found a newline at line 34
```

It seems that tables cannot be spread over multiple lines

**Comment by vitiral** [comment]
Confirmed that this still happens in toml 0.4.10

**Comment by vitiral** [comment]
I have also included a failing test.

**Comment by ehuss** [comment]
This is part of the TOML spec, inline tables must be on one line.

**Comment by vitiral** [comment]
interesting, that is surprising!
