### ISSUE TITLE
Parsing enum keys from toml file

### ISSUE THREAD

**Issue by chinedufn** [alexcrichton/toml-rs#284]
I'm trying to parse a TOML file into a HashMap.

When I try to do this with serde-json it works just fine, so I'm thinking that I'm misusing or misunderstanding serde-toml.

My TOML file and Rust types (simplified):

```toml
[[Rocks]]
    [Rocks.EQUAL.Quest]
      quest_id = 1
      step = 3

```

Which I'd like to parse into `HashMap<Model, MyType>`

```rust
enum Model {
  Rocks
}

enum MyType {
  EQUAL(Criterion)
}

enum Criterion {
  Quest {quest_id = 1, step = 3}
}
```

Error:

```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: string \"Rocks\", expected enum Model", key: [] } }',
```

So it looks like it's recognizing `Rocks` as a String instead of a `Model`. Is there any way around this?

Cheers!

**Comment by chinedufn** [comment]
Ahhh you're right I misunderstood how to write maps in toml.

At any rate, an example of working JSON (commented out) and what I believe is the equivalent toml.

```
#{
#  "Rocks": {
#    "slot": "RightHand",
#    "ent_crit": {
#      "EQUAL": {
#        "Quest": {
#          "quest_id": 1,
#          "step": 3
#        }
#      }
#    }
#  }
#}

[Rocks]
  slot = "RightHand"
  [Rocks.ent_crit.EQUAL.Quest]
    quest_id = 1
    step = 3
```

> However, it looks like it doesn't support enums as map keys

Gotcha - I think that's my problem then. Cool cool I'll use json in the meantime - thanks a lot for the quick help!

> Can you show a complete (compilable) example that shows what you would expect to work in json vs toml?

Seems like this isn't needed anymore - but just lmk if it is.

**Comment by doivosevic** [comment]
Hi everyone. Has there been any progress with enums?

I can parse e.g. this:

```
data_source = { ingest_custom_data = { folder_pattern = "%Y%m%d", cloud_name = "Google", bucket_name = "events", only_files_with_pattern = ".*/qwe/.*" }}
```

but I would like to flatten this somehow to make it more readable
