### ISSUE TITLE
Q. walking on the values

### ISSUE THREAD

**Issue by porcevader** [alexcrichton/toml-rs#287]
Hi, thanks for this great crate.
It is not very obvious how to use iterators on the toml value, parsed by String.parse::<Value>.
Is there an idiomatic way to walk the values in sequence?

Thank you

**Comment by porcevader** [comment]
No worries. I just found that the result of parse::<Value> is in fact a Table, and the Table is a BTreeMap<>. So I can use iter().

One question though - If I use parse::<Value> on a String, does it always yield Table?

**Comment by alexcrichton** [comment]
Thanks for the question! Currently yeah this always parses into a table because that's what the TOML spec is, but you can use individual deserialize implementations to deserialize just small chunks of toml

**Comment by porcevader** [comment]
Thank you for the answer. If you feel comfortable, I have a follow up question:

Q1. What do you think of implementing iter(), directly on the Value?
Q2. My use case happened to require a slight more flexibility, and I expect fields / tables that were not known in advance. So rather than using serde, I opted to use the versatility of parse<Value>. In this case, the top level is always a Table. As of now I cannot pass the Table as a function parameter. It should be a Value always, and the receiving function needs to apply match statement to destruct(?) into a Table variant. Do you think it will be useful to allow to pass the Table directly?

**Comment by alexcrichton** [comment]
For implementing iter directly I think the different types of values means that it may not be easy to implement, because how would you iterate uniformly over arrays and tables?

I think you should be able to pass tables around directly as they have their own dedicated type?

**Comment by porcevader** [comment]
Re: the passing tables. I have tried and compiler did not like it. I will update with the error message next time I try again.

Re: the iter() for different types of values. Have not explored yet, but what do you think about this crate? Does it look useful?
https://docs.rs/strum/0.13.0/strum/
