### ISSUE TITLE
Bug when parsing floats with negative exponent.

### ISSUE THREAD

**Issue by quadrupleslap** [alexcrichton/toml-rs#288]
https://github.com/alexcrichton/toml-rs/blob/master/src/de.rs#L1172 is case-sensitive, which is wrong.

Example:

```
x = 1e-7 # parsed correctly
y = 1E-7 # not parsed correctly
z = 2018-10-10T10:10:10 # parsed correctly
z = 2018-10-10t10:10:10 # not parsed correctly (altho for other reasons)
```

**Comment by ehuss** [comment]
Indeed!  Are you interested in submitting a PR?  If not, I can take care of it.

**Comment by quadrupleslap** [comment]
i'm way too sleepy to be writing stuff now. :P thanks for fixing it!

**Comment by ehuss** [comment]
No problem, I'll try to take care of it soon.

The TOML spec is clear that it should be case-insensitive, so I think it definitely is just a bug.  Those clarifications to the spec are relatively recent, though, so maybe at the time it wasn't so clear.
