### ISSUE TITLE
PartialEq for toml::de::Error

### ISSUE THREAD

**Issue by omarabid** [alexcrichton/toml-rs#291]
toml::ser::Error implements the PartiqlEq Trait. The de::Error does not. Any particular reason for that? The trait is useful if you are managing errors with your own type.

**Comment by ehuss** [comment]
I don't know if there was a specific reason, but I think it should be fine to have the same traits as `ser::Error`.  Feel free to post a PR!

**Comment by omarabid** [comment]
Shouldn't you derive the trait for ErrorKind and ErrorInner too? I think maybe that was the issue? @alexcrichton  might gives us a clue here?

**Comment by ehuss** [comment]
Yes, it will be required for all 3 struct/enums.
