### ISSUE TITLE
New release including preserve_order

### ISSUE THREAD

**Issue by twe4ked** [alexcrichton/toml-rs#293]
Hi, any chance you can push a new release? I need the `preserve_order` flag from https://github.com/alexcrichton/toml-rs/pull/278.

Thanks!

**Comment by ehuss** [comment]
[0.5.0](https://github.com/alexcrichton/toml-rs/releases/tag/0.5.0) has been published, thanks!

**Comment by twe4ked** [comment]
Awesome, thanks very much!
