### ISSUE TITLE
Make serde dependency optional?

### ISSUE THREAD

**Issue by GuillaumeGomez** [alexcrichton/toml-rs#347]
I made a few tests and by not using serde, this crate would go from 10 secs to 0.9 secs to compile. However, it also doesn't anything anymore considering that the entry point is the `from_str` function which only works with serde... (which means that the numbers I gave is mostly useless)

Would it be possible to do it? I can provide the PR I started if you want?

**Comment by alexcrichton** [comment]
No at this time this crate critically relies on serde, so it can't be removed unfortunately.
