### ISSUE TITLE
Publicly expose de::ErrorInner

### ISSUE THREAD

**Issue by Luthaf** [alexcrichton/toml-rs#360]
I would like to customize the error message on deserialization failure, and it looks like most of the data is already there in `de::ErrorInner`, but the struct is private

https://github.com/alexcrichton/toml-rs/blob/75129040cd041b380f4f1d8f2685928392aa9f55/src/de.rs#L93-L100

Would you be OK with exposing `ErrorInner` publicly, either through a `Deref` implementation or by forwarding some getters to access its fields?  `line` and `col` are already accessible through `de::Error::line_col()`.

If you agree, I am happy to make a PR for this.

**Comment by alexcrichton** [comment]
Thanks for the report! This is an internal error though and would need design for actually being exposed, so I would prefer to not just mark this `pub` and reexport it. If you'd like to add a new constructor though and/or setters/getters, seems fine to add those in a PR!
