### ISSUE TITLE
Serializing Vector of Struct T

### ISSUE THREAD

**Issue by alalfakawma** [alexcrichton/toml-rs#395]
Hello, I have done a lot of reading but have not seen anyone with this same problem. Or I may have missed it. I'm trying to serialize a `Vec<T>` where `T` is a struct with 2 fields. The output of the `toml::to_string()` function outputs it as follows:
```toml
[[]]
field1 = "string"
field2 = false
```
And this works with no errors. But the biggest problem is it cannot be deserialized because of `[[]]` brackets as it will throw an error -
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Wanted { expected: "a table key", found: "a right bracket" }, line: Some(0), col: 2, at: Some(2), message: "", key: [] } }', src/main.rs:251:5
```
I'm kind of new to Rust and i'm not sure if this is a place to post it but I would really appreciate it if someone could guide me with it.

**Comment by alexcrichton** [comment]
This is a bug that should be fixed in this crate to return an error instead of silently succeeded (or auto-using inline tables), but in general tables only really work as a top-level serialization.

**Comment by alalfakawma** [comment]
> This is a bug that should be fixed in this crate to return an error instead of silently succeeded (or auto-using inline tables), but in general tables only really work as a top-level serialization.

Thanks for the reply. Sorry but, can you please explain what you mean by 

> but in general tables only really work as a top-level serialization.
I'm not really sure if you're saying it is not possible to do what I'm trying to do or there is another specific way of doing it.

**Comment by ehuss** [comment]
@alalfakawma You need to place the vec into a container.  TOML works with key/value pairs, and that means a map or struct.  Example:

```rust
#[derive(Serialize)]
struct Foo {
    f1: i32,
}
// Instead of this...
let foos = vec![Foo{f1: 1}, Foo{f1: 2}];
println!("{}", toml::to_string(&foos).unwrap());

// Do this:
#[derive(Serialize)]
struct Container {
    foos: Vec<Foo>,
}
let b = Container{foos};
println!("{}", toml::to_string(&b).unwrap());
```

`to_string` should not be accepting non-map types.

**Comment by alalfakawma** [comment]
> types

Good point. Now I need to refactor my code 😅 to use the container. Thanks for the help guys.
