### ISSUE TITLE
[help]: Deserialization throws weird error that doesn't make sense

### ISSUE THREAD

**Issue by SirWindfield** [alexcrichton/toml-rs#399]
I am currently reading in a configuration file from the file system. The file is read in correctly and does not contain any special characters. However, `toml` spits out an error that I can't comprehend:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: Some(7), col: 0, at: Some(76), message: "invalid type: map, expected option", key: [] } }', main\src\main.rs:71:57
```

The error is thrown on the empty line before the last `[[keys]]` (line 7).
I read the file using the following code in:
```rust
if let Some(config_path) = config_file_path() {
        info!("Found config: {}", config_path.display());

        let mut file = std::fs::File::open(config_path).unwrap();
        let mut content = String::new();
        file.read_to_string(&mut content).unwrap();

        //println!("{}", &content);

        twm.config = twm_core::toml::from_str(&content).unwrap(); // <--- error thrown on this unwrap.
    }
```

```toml
[taskbar]
show = true

[[keys]]
name = "tile.close"
value = "alt+q"

[[keys]]
name = "tile.swap.right"
value = "alt+shift+l"

```

```rust
#[derive(Debug, Default, Deserialize, Serialize)]
pub struct Config {
    pub keys: Vec<KeyEntry>,
    pub taskbar: TaskbarConfig,
}

#[derive(Debug, Default, Deserialize, Serialize)]
pub struct KeyEntry {
    name: String,
    value: String,
}

#[derive(Debug, Default, Deserialize, Serialize)]
pub struct TaskbarConfig {
    pub show: bool,
}
```

The thing is, it does work inside of a [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8c4757c4bfc68f5f38703f7bb0d1f3c4) when using a string literal. It's exactly the same code that I use.

I've added a test method for file access as well so that the code can just be copy-pasted if someone wants to try it out locally :)

**Comment by ehuss** [comment]
Hm, I don't see any clues as to what is happening. It shouldn't matter if it is from a file or a string literal. One possible difference there is if it has Windows newlines, but that shouldn't matter. 

I would try to attach with a debugger and see what it was doing when the error is raised (that comes from serde's `Error::invalid_type` method).  I would also double check that it is loading the file you are expecting.  Also, that error should only happen when serde is visiting an `Option`. I don't see any options in your types, so that is very curious.

**Comment by SirWindfield** [comment]
Weirdly enough, I set a breakpoint inside of `toml::de::from_str` on line 80 (`let ret = T::deserialize(&mut d)`). When stepping into it, the debugger brings me to this `impl`:

```
impl<'de, T> Deserialize<'de> for Option<T>
where
    T: Deserialize<'de>,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_option(OptionVisitor {   // <---- debugger continues here after one single step-into from the above line (80).
            marker: PhantomData,
        })
    }

    // The Some variant's repr is opaque, so we can't play cute tricks with its
    // tag to have deserialize_in_place build the content in place unconditionally.
    //
    // FIXME: investigate whether branching on the old value being Some to
    // deserialize_in_place the value is profitable (probably data-dependent?)
}
```

This would explain the error I think. Now is the question why exactly it uses that implementation.

**Comment by SirWindfield** [comment]
Ahhhhh, user error! I assigned the `unwrap`ped value to a field of type `Option<Config>`, I just forgot to wrap the result into `Some`.

My bad!
