### ISSUE TITLE
Is it possible to return all errors instead of just the first encountered error?

### ISSUE THREAD

**Issue by pjmp** [alexcrichton/toml-rs#400]
Hello, is it possible to return all errors instead of just the first encountered error. I was trying to write a toml validator and it would be great to have this feature. Thanks anyways.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d952da56e425265e7faf2c036db3bd72)
```rust
const RAW: &str = "
ip = '127.0.0.1'

ip = 'some'

foo = 'bar'

bar = 1

[keys]
github = 'xxxxxxxxxxxxxxxxx'
travis = 'yyyyyyyyyyyyyyyyy'
";

use toml;
use toml::Value;

fn main() {
    let _ = match RAW.parse::<Value>() {
        Ok(e) => e,
        Err(e) => {
            println!("{:#?}", e);
            std::process::exit(1)
        }
    };
}

/*  error
Error {
    inner: ErrorInner {
        kind: Custom,
        line: Some(
            9,
        ),
        col: 0,
        at: Some(
            54,
        ),
        message: "duplicate key: `ip`",
        key: [],
    },
}
*/
```

Expected:
Vec of errors.

**Comment by alexcrichton** [comment]
Currently the deserializer/parser isn't structured to recover from errors, so an list of errors cannot be returned.

**Comment by pjmp** [comment]
Ah okay, thanks for taking time to response.
