### ISSUE TITLE
Spanned documentation is missing from rustdoc again

### ISSUE THREAD

**Issue by roblabla** [alexcrichton/toml-rs#408]
Basically #309 regressed. Seems to be caused by https://github.com/alexcrichton/toml-rs/commit/d99f5665b420f570c4aa26602360f7d5eaee1dc9. I think the `doc(no_inline)` should be removed again, or the spanned module made public?

**Comment by ehuss** [comment]
Yea, I'm not sure why the `no_inline` was added.  @bgeron  can you clarify why `no_inline` was added in #377?

**Comment by bgeron** [comment]
Shoot. I didn’t realize that that introduced a bug. I think we should revert both of the no_inline lines I added in that commit. Sorry!

I guess my rationale was stylistic reasons, not important. 

Can you revert the two lines for me please?

Thanks!

Am Mo, 2. Nov 2020, um 00:58, schrieb Eric Huss:

**Comment by bgeron** [comment]
Great find!

Am Mo, 2. Nov 2020, um 07:13, schrieb Bram Geron:
