### ISSUE TITLE
error: method `emit_enum_struct_variant` has 0 type parameters but its trait declaration has 1 type parameter

### ISSUE THREAD

**Issue by emk** [alexcrichton/toml-rs#41]
Good morning! `toml` seems to have been broken by the closure updates and the changes to `Encoder` and `Decoder`:

> toml-0.1.4/src/serialization.rs:222:5: 228:6 error: method `emit_enum_struct_variant` has 0 type parameters but its trait declaration has 1 type parameter [E0049]

I'm trying to fix this in one of my own libraries, and it's trickier than I expected.

**Comment by alexcrichton** [comment]
Fixed some time ago I believe
