### ISSUE TITLE
Please yank v0.5.0 and v0.5.1

### ISSUE THREAD

**Issue by Tamschi** [alexcrichton/toml-rs#412]
Hi,

[I'm having some issues with `-Z minimal-versions` CI for one of my projects](https://github.com/Tamschi/Asteracea/pull/26), due to a mistaken `serde = "1.0"` dependency in this crate's 0.5.1 (and 0.5.0) version(s), as follows:

```
[…]> cargo update -Z minimal-versions && cargo build
    Updating crates.io index
    Updating serde v1.0.117 -> v1.0.0
    Updating toml v0.5.7 -> v0.5.1   
  Downloaded serde v1.0.0
  Downloaded toml v0.5.1
  Downloaded 2 crates (109.5 KB) in 2.04s
   Compiling serde v1.0.0
   Compiling toml v0.5.1
error[E0432]: unresolved import `serde::de::value::BorrowedStrDeserializer`
  --> […]\toml-0.5.1\src\de.rs:15:5
[…]
```

This seems to have been noticed and fixed in 0.5.2, but as long as 0.5.0 and 0.5.1 are unyanked, they can still be resolved as minimal version.
Conversely, yanking 0.5.0 and 0.5.1 would fix the problem transitively for all dependants that don't have that exact version pinned.

**Comment by Tamschi** [comment]
I just ran into this problem again, but this time regarding 0.5.0, so I updated the issue in that regard.

**Comment by Tamschi** [comment]
Sorry if this nudges you during the holidays. It's not a pressing pressing issue for me personally, but if I don't file this now, I'll 100% forget to sort it out on my end.

**Comment by ehuss** [comment]
I went ahead and yanked those two versions.

**Comment by Tamschi** [comment]
It's working perfectly now, thank you!
