### ISSUE TITLE
Cannot find serde_derive

### ISSUE THREAD

**Issue by ruffson** [alexcrichton/toml-rs#419]
Hi there,
I am feeling silly asking this as it seems like I am doing something very obvious wrong but after spending a lot of time I cannot get a simple deserialization to work.

I'm trying to use `toml::from_str(...)` to deserialize a toml file. I added the depencency `toml = "0.5"` to my `Cargo.toml` but when I try to import like in the example with: `use serde_derive::Deserialize;` I get a:
```
use of undeclared crate or module `serde_derive`
```
I haven't worked with serde yet but it is a dependency of this repo so I don't seem to have to import it separately.

(I feel like I have been coding for too long and now fail at the simplest tasks, apologies!)

**Comment by ehuss** [comment]
To use `serde_derive`, you have two options:

* Add `serde_derive = "1.0"` to `Cargo.toml`.
* Add `serde = { version = "1.0", features = ["derive"] }`, and then instead of `serde_derive::Deserialize`, you use `serde::Deserialize` (or `use serde::Deserialize` if you'd prefer to create a shorter alias of just `Deserialize`).

There's more at https://serde.rs/derive.html about this.

**Comment by ruffson** [comment]
Thank you so much! Maybe this should go somewhere in the documentation as this is not quite obvious.

**Comment by ruffson** [comment]
Okay just to add to this, if I just add the crate `serde_derive` to my `Cargo.toml` to follow the docs, I can now properly import but still cannot just use `Deserialize` in the `derive`:

```rust
5 | #[derive(Debug, Deserialize)]
  |                 ^^^^^^^^^^^ can't find crate
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `my_app`

To learn more, run the command again with --verbose.
```

So it seems only explicitly using `serde` works.
