### ISSUE TITLE
Convert toml::Value to Rust struct

### ISSUE THREAD

**Issue by vedantroy** [alexcrichton/toml-rs#421]
I know I can use serde to deserialize a TOML string directly into a struct, but, I was wondering if it was possible to deserialize a toml Value into a struct.

This would allow dynamic deserialization of certain parts of a toml document & pre-defined serialization for other parts of a toml document.

**Comment by ehuss** [comment]
Yes, [`try_into`](https://docs.rs/toml/0.5.8/toml/value/enum.Value.html#method.try_into) and [`try_from`](https://docs.rs/toml/0.5.8/toml/value/enum.Value.html#method.try_from) can be used to convert into or from a Value with any arbitrary type that implements Serialize or Deserialize.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7687894bcbfb8e555e09ef6819af4bf5
