### ISSUE TITLE
make `Datetime` fields publically accessible

### ISSUE THREAD

**Issue by samuelcolvin** [alexcrichton/toml-rs#431]
I mentioned this on #159, but it's slightly different and I thought deserved a separate issue.

I'd like to be able to access the fields of `Datetime` (and then obviously `Date` and `Time`) directly rather than having to re-parse the result of `to_string()`.

I don't need chrono integration, just direct access to the integer values.

Currently in rtoml I'm using `std::mem::transmute` into duplicated structs in order to access the fields which as well as being ugly and `unsafe` means multiple copies.

For anyone else needing this, you can see the code [here](https://github.com/samuelcolvin/rtoml/blob/78ebad15f8d94b42fc7ada2a7ac7fd67e620216f/src/datetime.rs#L8-L38).

Would you accept a PR for this?

---

Also, (perhaps separate issue) I think `offset` should be moved into `date` since AFAIK times with timezone are not valid in toml.

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

**Comment by xpe** [comment]
@samuelcolvin I created a pull request over at #439

**Comment by xpe** [comment]
@samuelcolvin This got merged in [83d787c60](https://github.com/alexcrichton/toml-rs/commit/83d787c60dbaaaf5b769f0948a5e8760ea5695cf). Does the PR meet your needs? If so, could you close this issue?

**Comment by samuelcolvin** [comment]
It looks great, either your can close it now or I'll try and use it in rtoml next week.

**Comment by xpe** [comment]
@samuelcolvin Good :). I can't close this, because I don't have "close issue" privileges. Sometimes I like to do some issue gardening.

**Comment by ehuss** [comment]
Thanks @xpe!  It sounds like this is done, so I'll close it out.

**Comment by not-my-profile** [comment]
Thanks for implementing this! I'd love to use it in a project I want to publish on crates.io, would it be possible to release a new version of the `toml` crate?
