### ISSUE TITLE
about examples/decode.rs

### ISSUE THREAD

**Issue by JesseAtSZ** [alexcrichton/toml-rs#434]
I am writing a program based on this example：
https://github.com/alexcrichton/toml-rs/blob/master/examples/decode.rs

I have the following questions about this example：

If toml_str has a field that is not named in the structure, for example, I mistakenly wrote ip as ips, I found that the ip value in the parsed ServerConfig is none, but for me, an illegal field appears in the toml file, I hope to report an error. What should I do?

"global_string" in the toml file is underlined. If I want to change "global_string" in the toml file to "global-string", how should "global_string" in the config structure be changed?

**Comment by ehuss** [comment]
To detect unknown fields, you should use [`serde_ignored`](https://crates.io/crates/serde_ignored).

To convert underscores and dashes, you can use serde renaming, such as the attribute `#[serde(rename_all="kebab-case")]`. More information can be found in the [serde documentation](https://serde.rs/).

**Comment by jonasbb** [comment]
There is also [`#[serde(deny_unknown_fields)] `](https://serde.rs/container-attrs.html#deny_unknown_fields) for creating a deserialization error when unknown fields are observed.
