### ISSUE TITLE
How to parse dynamic type like Cargo did

### ISSUE THREAD

**Issue by axetroy** [alexcrichton/toml-rs#461]
```toml
tokio = { version = "1", features = ["full"] }
chrono = "0.4.19"
```

**Comment by ehuss** [comment]
The key part is to use an enum with `#[serde(untagged)]`, like this:

```rust
#[derive(Deserialize)]
struct Description {
    version: String,
    features: Vec<String>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum Either {
    Detailed(Description),
    Simple(String),
}
```

For various reasons, cargo itself uses a custom deserializer (like [this](https://github.com/rust-lang/cargo/blob/109bfbd055325ef87a6e7f63d67da7e838f8300b/src/cargo/util/toml/mod.rs#L198-L245)).

For questions about using a common library like serde, I suggest trying one of the user forums like https://users.rust-lang.org/.  Also, serde has a manual at https://serde.rs/ that explains various ways to use it.
