### ISSUE TITLE
fails to build rust 1.0.0 alpha

### ISSUE THREAD

**Issue by mossplix** [alexcrichton/toml-rs#52]
fails to build rust 1.0.0 alpha  
Compiling toml v0.1.15 (https://github.com/alexcrichton/toml-rs#0a6a1cab)
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/parser.rs:31:10: 31:15 error: unknown `derive` trait: `Debug`
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/parser.rs:31 #[derive(Debug)]
                                                                                               ^~~~~
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:69:10: 69:15 error: unknown `derive` trait: `Debug`
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:69 #[derive(Debug)]
                                                                                                      ^~~~~
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:85:21: 85:26 error: unknown `derive` trait: `Debug`
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:85 #[derive(PartialEq, Debug)]
                                                                                                                 ^~~~~
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:94:21: 94:26 error: unknown `derive` trait: `Debug`
/Users/mossplix/.cargo/git/checkouts/toml-rs-73fb57c92ca3f82c/master/src/serialization.rs:94 #[derive(PartialEq, Debug)]
                                                                                                                 ^~~~~
error: aborting due to 4 previous errors
Could not compile `toml`.

**Comment by alexcrichton** [comment]
Thanks for the report! This tip of this repository is intended to build with the master branch of rustc, however. I'd recommend keeping up to date with the latest Rust nightly and this will likely all smooth over :)
