### ISSUE TITLE
off by one bug

### ISSUE THREAD

**Issue by MarkSwanson** [alexcrichton/toml-rs#59]
The Parser to_linecol() fn returns zero-based lines.
It should be one-based:

```
$ git diff
diff --git a/src/parser.rs b/src/parser.rs
index 377da24..bec7cd8 100644
--- a/src/parser.rs
+++ b/src/parser.rs
@@ -79,7 +79,7 @@ impl<'a> Parser<'a> {
         let mut cur = 0;
         for (i, line) in self.input.lines().enumerate() {
             if cur + line.len() > offset {
-                return (i, offset - cur)
+                return (i + 1, offset - cur)
             }
             cur += line.len() + 1;
         }
```

**Comment by alexcrichton** [comment]
Thanks for the issue! In [the documentation, however](http://alexcrichton.com/toml-rs/toml/struct.Parser.html#method.to_linecol), I made sure to state that both of these indexes are 0-based instead of 1-based. Did you find that the columns were 1-based though?

**Comment by MarkSwanson** [comment]
Er... I don't know why my brain completely skipped over that.
Your code is working as documented. I'll simply +1 the values in my error handler.
Sorry for the noise.

**Comment by alexcrichton** [comment]
No worries, thanks for checking regardless!
