### ISSUE TITLE
Value doc wrong

### ISSUE THREAD

**Issue by MarkSwanson** [alexcrichton/toml-rs#62]
Page: http://alexcrichton.com/toml-rs/toml/enum.Value.html

Code: let value: toml::Value = toml.parse().unwrap();

The types are wrong, and it won't compile.
parse() returns a BTreeMap<String, Value>

I like what the docs are saying. It would be great if I could parse and use lookup() on the result.
Currently you have to:
- parse
- lookup the first key
- Option test the value, then use lookup()

**Comment by alexcrichton** [comment]
Thanks for the report! I think this should work, however, as it's a test that's auto-run by rustdoc. The `parse()` call is actually using the `FromStr for Value` implementation, not the `Parser`'s parsing method.

If you're directly using `Parser::parse` you may want to take the return value and wrap it up in a `Value::Table` which you should then be able to use `.lookup()` on directly.
