### ISSUE TITLE
Allow for literal strings in key names

### ISSUE THREAD

**Issue by jethrogb** [alexcrichton/toml-rs#85]
I assume this is already on your radar, but I think it's important that this gets implemented soon: this parser currently rejects literal strings in key names, but people might want to use this syntax in Cargo in the not so distant future. That means people with an old version of Cargo (built with an old version of toml-rs) will not be able to parse those newer crate manifests. The only way to prevent this is to start shipping an updated parser soon.

**Comment by alexcrichton** [comment]
It is indeed! I'll be sure to issue a version bump before the support lands in Cargo so Cargo can be sure to leverage it as well.
