### ISSUE TITLE
Upgrade to serde 0.7

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/toml-rs#87]
It'd be nice to bump the serde support to 0.7

**Comment by alexcrichton** [comment]
Ah right yes indeed!

I've got a [work in progress branch](https://github.com/alexcrichton/toml-rs/tree/serde-0.7) which at least compiles, although I don't know what changed in 0.7 and there are a number of failing tests, so it's not quite ready yet.

**Comment by alexcrichton** [comment]
Ok, fixed one more test and tracked down the remaining bugs. Unfortunately it looks like there's [breakage in 0.7](https://github.com/serde-rs/serde/issues/267) relative to 0.6 which causes tests to fail.

**Comment by sfackler** [comment]
This was fixed a while ago.
