### ISSUE TITLE
Enum decode/encode does not correspond properly to Rust types

### ISSUE THREAD

**Issue by apoelstra** [alexcrichton/toml-rs#9]
The current TOML parser uses Rust enums as a way to get "variable type" fields. That is, if you have an enum like this
````
enum MyEnum {
  One(uint),
  Two(f64)
}
````
The corresponding TOML is that a floating-point value is interpreted as a `Two(num)` while an integer is interpreted as a `One(num)`.

However, this does not interact well with C-like enums at all: with the current code, if you have an enum like
````
enum MyEnum {
  One,
  Two
}
````
then any TOML at all will decode to `One`, since the decoder code just runs through the enum variants until one parses successfully. For C-like enums, the first one always will.

What would be nice (and more importantly, expected) is if I could use C-like enums as keys in a HashMap and have the values under `[One]` go to one HashMap value while the values under `[Two]` go to another.

**Comment by alexcrichton** [comment]
This is pretty old at this point, but I'm going to close this as basically "this is a limitation of using TOML as a configuration format".
