### ISSUE TITLE
Get the position of a Value in the file

### ISSUE THREAD

**Issue by Luthaf** [alexcrichton/toml-rs#95]
It would be nice for error reporting to be able to get the position (the span) of a specific TOML value in the file. 

For example, I am parsing a configuration file for my project, and the user entered a string where an integer is needed. I would like to report the position of the error in addition with the usual `"this key must be an integer"` message.

I do not know how hard this would be to implement, and how the API could look like. Having something like

``` rust
struct Span {
    file: Path,
    line_start: usize,
    line_end: usize,
    col_start: usize,
    col_end: usize,
}

enum Value {
    String(String, Span),
    Integer(i64, Span),
    Float(f64, Span),
    Boolean(bool, Span),
    Datetime(String, Span),
    Array(Array, Span),
    Table(Table, Span),
}
```

would be rather inconvenient to use. Maybe something like that, with a duplication of methods on `Value` and `Entry`.

``` rust
struct Entry {
    value: Value,
    span: Span
}
```

If you think this is not too hard, I can give it a try.

**Comment by alexcrichton** [comment]
Unfortunately this can't be easily done today without basically rewriting the parser, but there's some support in the `toml_document` crate.

I've been meaning to rewrite the parser, though, to support operations like this, and I'd always be willing to take a PR!

**Comment by mehcode** [comment]
@alexcrichton Has any progress been made on this? I'd like to try and contribute here. 

I'm thinking of rewriting the parser into a stream that generates an `Event`. Something like https://dtolnay.github.io/serde-yaml/yaml_rust/parser/enum.Event.html but much simpler as this is TOML.

That's all I need for my use case (which is actually the same use case as @Luthaf. @Luthaf if you're still pursuing this, come over to https://github.com/mehcode/config-rs and let's chat).

Thoughts?

**Comment by alexcrichton** [comment]
@mehcode unfortunately no not much progress has happened here :(

In terms of an implementation this crate "should be ready" in the sense that all parsing is based on https://github.com/alexcrichton/toml-rs/blob/master/src/tokens.rs which should be a lossless tokenization of the original input, preserving whitespace and comments. While "spans" aren't necessarily I think all tokens have an exact correspondance to the original string.

Most of the work now at this point is figuring out how to best expose this, which I'm not sure how to do :(

**Comment by est31** [comment]
In #327 it was decided to pursue SpannedValue addition via an entirely separate crate. It's available at https://github.com/est31/toml-spanned-value

**Comment by est31** [comment]
The crate isn't using a forked version of toml-rs any more and I've [uploaded it to crates.io](https://crates.io/crates/toml-spanned-value). I think this should be resolved now.

**Comment by Luthaf** [comment]
thanks a lot @est31 ! I'll try using your crate when I get the time to =)

**Comment by alexcrichton** [comment]
👍
