### ISSUE TITLE
Datetimes aren't quite ISO 8601 compliant

### ISSUE THREAD

**Issue by HeroesGrave** [alexcrichton/toml-rs#96]
Two things are missing that have caused me issues:

- Parsing fails with timezone offsets.
- Parsing fails with decimal fractions in the time components. (This is slightly less of a problem).

[chrono](https://crates.io/crates/chrono) should be able to handle it fairly easily and help clean up the [parsing method](https://github.com/alexcrichton/toml-rs/blob/master/src/parser.rs#L724-L771).

**Comment by alexcrichton** [comment]
Thanks for the report! I've tweaked the parser a bit and I think it should work now, wanna give it a spin?

**Comment by HeroesGrave** [comment]
Working correctly now. Thanks
