### ISSUE TITLE
[0.1.30] Value::String::to_string() returns quoted string

### ISSUE THREAD

**Issue by sanmai-NL** [alexcrichton/toml-rs#97]
Is that intentional? It caught me by surprise. I couldn't find enough info about the purpose and/or expected results of this trait method in https://doc.rust-lang.org/std/string/trait.ToString.html. 

It seems it isn't being done across implementers.
```rust
println!("quoted? {}", 1.to_string());
println!("quoted? {}", "hello".to_string());
```
outputs: 
```
quoted? 1
quoted? hello
```

## Meta
```
  rustc --version --verbose
rustc 1.8.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.8.0

```

**Comment by alexcrichton** [comment]
This is currently intentional, yeah, and mirrors the behavior of strings in Rust, for example.
