### ISSUE TITLE
Accepts invalid datetimes

### ISSUE THREAD

**Issue by zofrex** [alexcrichton/toml-rs#99]
For example this input is accepted as valid:

```
foo=1000-00-00T00:00:00Z
```

My reading of RFC 3339 is that this is not valid, both day and month should be >= 1.

I can take a swing at fixing this but I'm not sure what the right approach would be. Maybe to add in a date time parsing library and offload the work onto that?

**Comment by alexcrichton** [comment]
Interesting! The [proposed ABNF](https://github.com/toml-lang/toml/pull/236) indicates that any two digits are accepted, but a comment to the side indicates that 00 shouldn't be accepted. I'll flag this over there and see what others think.

**Comment by alexcrichton** [comment]
Ah nevermind this is a grammatical vs validation difference. The ABNF for these times is taken verbatim from the RFC, this is just an extra layer of validation that needs to be performed.

**Comment by alexcrichton** [comment]
Hm so I'm not sure what to do about this actually. This *could* depend on perhaps a more full-featured library that does all sorts of parsing/validation to ensure it's a valid RFC 3339 date, but the current implementation is pretty simple and there's not a clear dependency to me to pick up.

I'd probably punt this to 0.2 whenever it happens as the `Datetime` type probably really shouldn't contain a `String` but rather some form of parsed date anyway. It also looks like date/time types may be tweaked a bit in the TOML spec so may be worth waiting for that to shake out as well.

**Comment by alexcrichton** [comment]
I've rewritten the parser in the serde 0.9 rewrite https://github.com/alexcrichton/toml-rs/pull/137, and I've added simple validation like this now that `Datetime` is its own actual parsed type.

**Comment by alexcrichton** [comment]
Fixed in #137
